name: crypto_flow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  get_it: ^7.6.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  http: ^1.4.0

flutter:
  uses-material-design: true